version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "installing dependencies"
      - npm install
  build:
    commands:
      - echo "building"
      - npm run build
  post_build:
    commands:
      - echo "Clear S3 bucket"
      - aws s3 rm --recursive "s3://${ARTIFACTS_BUCKET}/"
artifacts:
  files:
    - './**/*'
  base-directory: public
