version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "installing dependencies"
      - npm install
  build:
    commands:
      - echo "building"
      - npm run build
artifacts:
  files:
    - './**/*'
  base-directory: public
