name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        npm install
        npm run build
        
    - name: Deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd ${{ github.workspace }}/public
        git init
        git add .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Build artifacts"
        github_repo="https://x-access-token:$GITHUB_TOKEN@github.com/danielkhoo/danielkhoo.github.io.git"
        echo $github_repo
        git push --set-upstream $github_repo master
        git push --force $github_repo
        
        
        
        
